id: ICB3CE293
legacy_id: P008161
ocr_import_info:
  bdrc_scan_id: W1KG18562
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T13:51:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:48:19.581400+00:00'
last_modified: 2022-08-31 17:48:56.407259
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG18562
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG18562
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྙིགས་དུས་འགྲོ་བ་ཡོངས་ཀྱི་སྐྱབས་མགོན་ཞབས་དཀར་རྡོ་རྗེ་འཆང་ཆེན་པོའི་རྣམ་པར་ཐར་པ་རྒྱས་པར་བཤད་པ།
  author: ཞབས་དཀར་བ་ཚོགས་དྲུག་རང་གྲོལ།
statistics:
  ocr_word_mean_confidence_index: 0.7124020881440369
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I1KG18596:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18596
      total_pages: 616
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18596.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7088866616483097
    legacy_id: v001
  I1KG18597:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18597
      total_pages: 596
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG18597.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7163761554226007
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
